# Generated by Django 4.2.26 on 2025-11-10 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The tag name (e.g., 'vegan', 'dessert', 'gluten-free')", max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The name of the recipe (e.g., 'Chocolate Chip Cookies')", max_length=200)),
                ('description', models.TextField(help_text='A brief description of the recipe')),
                ('image_url', models.URLField(blank=True, help_text='URL to an image of the finished recipe (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this recipe was first created')),
                ('author', models.ForeignKey(help_text='The user who created this recipe', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags that categorize this recipe (e.g., vegan, dessert, gluten-free)', to='recipes.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='The order of this step (1, 2, 3, etc.)')),
                ('instruction_text', models.TextField(help_text='The instruction for this step')),
                ('recipe', models.ForeignKey(help_text='The recipe this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Personal notes about this recipe (e.g., 'I prefer to replace cilantro with parsley')")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this recipe was added to favorites')),
                ('recipe', models.ForeignKey(help_text='The recipe that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='recipes.recipe')),
                ('user', models.ForeignKey(help_text='The user who favorited this recipe', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
