# Generated by Django 4.2.26 on 2025-11-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the finished recipe (optional)', null=True, upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an image of the finished recipe (optional, alternative to image upload)', null=True),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the ingredient (e.g., 'Flour', 'Sugar', 'Eggs')", max_length=200)),
                ('amount', models.CharField(blank=True, help_text="The amount needed (e.g., '2 cups', '1/2 teaspoon', '3')", max_length=50)),
                ('recipe', models.ForeignKey(help_text='The recipe this ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
