# Generated by Django 4.2.26 on 2025-11-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Recipe ingredients, one per line'),
        ),
    ]
