# Generated by Django 4.2.26 on 2025-11-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, help_text='Cooking time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('cuisine', 'Cuisine Type'), ('dietary', 'Dietary Restriction'), ('other', 'Other')], default='other', help_text='The category of this tag (cuisine, dietary, or other)', max_length=20),
        ),
    ]
