# Generated by Django 4.2.26 on 2025-11-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cook_time_recipe_prep_time_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_author',
            field=models.CharField(blank=True, help_text="The original recipe author or creator (e.g., 'Jamie Oliver', 'Grandma's Recipe')", max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL to the original recipe source (optional)', null=True),
        ),
    ]
