# Generated by Django 4.2.26 on 2025-11-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_recipe_author_recipe_source_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTestImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[("A", "Variant A"), ("B", "Variant B")], max_length=1
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
